// 区间月方向不能为空,余额不能为0
export let keMuMingXiTablePrintData =  {
    'list': [{
      'qichu': {'money': 40436.38, 'jie': 0, 'dir': '借', 'dai': 0},
      'kuaiJiKeMuCode': '1001',
      'kuaiJiKeMuCodeName': '库存现金',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '145361.30',
        'yearJieFangSum': '93371.00',
        'monthDir': '借',
        'monthJieFangSum': '93371.00',
        'yearDaiFangSum': '145361.30',
        'details': [{
          'rowJieFangMoney': '93371.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '第一季度普票收入',
          'type': '记-003',
          'rowMoney': '93371.00',
          'pingZhengNum': 'PZ000000186'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '5291.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '发放工资',
          'type': '记-005',
          'rowMoney': '88080.00',
          'pingZhengNum': 'PZ000000188'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '5291.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '发放工资',
          'type': '记-006',
          'rowMoney': '82789.00',
          'pingZhengNum': 'PZ000000189'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '5291.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '发放工资',
          'type': '记-007',
          'rowMoney': '77498.00',
          'pingZhengNum': 'PZ000000190'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '129488.30',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '结转成本',
          'type': '记-008',
          'rowMoney': '51990.30',
          'pingZhengNum': 'PZ000000191'
        }],
        'monthMoney': '51990.30'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '93371.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '145361.30',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '1001 - 库存现金'
    }, {
      'qichu': {'money': 546892.94, 'jie': 0, 'dir': '借', 'dai': 0},
      'kuaiJiKeMuCode': '1002',
      'kuaiJiKeMuCodeName': '银行存款',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '623.51',
        'yearJieFangSum': '59777.10',
        'monthDir': '借',
        'monthJieFangSum': '59777.10',
        'yearDaiFangSum': '623.51',
        'details': [{
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '623.51',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '缴所得税',
          'type': '记-001',
          'rowMoney': '623.51',
          'pingZhengNum': 'PZ000000184'
        }, {
          'rowJieFangMoney': '59777.10',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '第一季度代开收入',
          'type': '记-002',
          'rowMoney': '60400.61',
          'pingZhengNum': 'PZ000000185'
        }],
        'monthMoney': '60400.61'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '59777.10',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '623.51',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '1002 - 银行存款'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '221101',
      'kuaiJiKeMuCodeName': '应付职工工资',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '15900.00',
        'yearJieFangSum': '15900.00',
        'monthDir': '平',
        'monthJieFangSum': '15900.00',
        'yearDaiFangSum': '15900.00',
        'details': [{
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '5300.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '计提1月工资',
          'type': '记-005',
          'rowMoney': '5300.00',
          'pingZhengNum': 'PZ000000188'
        }, {
          'rowJieFangMoney': '5300.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '发放工资',
          'type': '记-005',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000188'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '5300.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '计提2月工资',
          'type': '记-006',
          'rowMoney': '5300.00',
          'pingZhengNum': 'PZ000000189'
        }, {
          'rowJieFangMoney': '5300.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '发放工资',
          'type': '记-006',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000189'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '5300.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '计提3月工资',
          'type': '记-007',
          'rowMoney': '5300.00',
          'pingZhengNum': 'PZ000000190'
        }, {
          'rowJieFangMoney': '5300.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '发放工资',
          'type': '记-007',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000190'
        }],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '2211 - 应付职工薪酬'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '222102',
      'kuaiJiKeMuCodeName': '未交增值税',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '1741.08',
        'yearJieFangSum': '468.13',
        'monthDir': '贷',
        'monthJieFangSum': '468.13',
        'yearDaiFangSum': '1741.08',
        'details': [{
          'rowJieFangMoney': '468.13',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '缴增值税',
          'type': '记-001',
          'rowMoney': '468.13',
          'pingZhengNum': 'PZ000000184'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '1741.08',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '第一季度代开收入',
          'type': '记-002',
          'rowMoney': '2209.21',
          'pingZhengNum': 'PZ000000185'
        }],
        'monthMoney': '2209.21'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '468.13',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '1741.08',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '2221 - 应交税费'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '222115',
      'kuaiJiKeMuCodeName': '应交所得税',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '149.38',
        'yearJieFangSum': '116.68',
        'monthDir': '贷',
        'monthJieFangSum': '116.68',
        'yearDaiFangSum': '149.38',
        'details': [{
          'rowJieFangMoney': '116.68',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '缴所得税',
          'type': '记-001',
          'rowMoney': '116.68',
          'pingZhengNum': 'PZ000000184'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '149.38',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '计提所得税',
          'type': '记-009',
          'rowMoney': '266.06',
          'pingZhengNum': 'PZ000000192'
        }],
        'monthMoney': '266.06'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '116.68',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '149.38',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '2221 - 应交税费'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '222117',
      'kuaiJiKeMuCodeName': '应交城市维护建设税',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '43.52',
        'yearJieFangSum': '11.70',
        'monthDir': '贷',
        'monthJieFangSum': '11.70',
        'yearDaiFangSum': '43.52',
        'details': [{
          'rowJieFangMoney': '11.70',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '缴附加税',
          'type': '记-001',
          'rowMoney': '11.70',
          'pingZhengNum': 'PZ000000184'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '43.52',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '计提税金及附加',
          'type': '记-004',
          'rowMoney': '55.22',
          'pingZhengNum': 'PZ000000187'
        }],
        'monthMoney': '55.22'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '11.70',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '43.52',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '2221 - 应交税费'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '222121',
      'kuaiJiKeMuCodeName': '应交个人所得税',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '27.00',
        'yearJieFangSum': '27.00',
        'monthDir': '贷',
        'monthJieFangSum': '27.00',
        'yearDaiFangSum': '27.00',
        'details': [{
          'rowJieFangMoney': '27.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '缴个税',
          'type': '记-001',
          'rowMoney': '27.00',
          'pingZhengNum': 'PZ000000184'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '9.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '发放工资',
          'type': '记-005',
          'rowMoney': '36.00',
          'pingZhengNum': 'PZ000000188'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '9.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '发放工资',
          'type': '记-006',
          'rowMoney': '45.00',
          'pingZhengNum': 'PZ000000189'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '9.00',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '发放工资',
          'type': '记-007',
          'rowMoney': '54.00',
          'pingZhengNum': 'PZ000000190'
        }],
        'monthMoney': '54.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '27.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '27.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '2221 - 应交税费'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '4103',
      'kuaiJiKeMuCodeName': '本年利润',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '5825.82',
        'yearJieFangSum': '0.00',
        'monthDir': '贷',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '5825.82',
        'details': [{
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '5825.82',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '期间损益结转',
          'type': '记-010',
          'rowMoney': '5825.82',
          'pingZhengNum': 'PZ000000193'
        }],
        'monthMoney': '5825.82'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '5825.82',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '4103 - 本年利润'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '6001',
      'kuaiJiKeMuCodeName': '主营业务收入',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '149378.18',
        'yearJieFangSum': '149378.18',
        'monthDir': '平',
        'monthJieFangSum': '149378.18',
        'yearDaiFangSum': '149378.18',
        'details': [{
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '58036.02',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '第一季度代开收入',
          'type': '记-002',
          'rowMoney': '58036.02',
          'pingZhengNum': 'PZ000000185'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '91342.16',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '第一季度普票收入',
          'type': '记-003',
          'rowMoney': '149378.18',
          'pingZhengNum': 'PZ000000186'
        }, {
          'rowJieFangMoney': '149378.18',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '期间损益结转',
          'type': '记-010',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000193'
        }],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '6001 - 主营业务收入'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '630101',
      'kuaiJiKeMuCodeName': '政府补贴',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '2028.84',
        'yearJieFangSum': '2028.84',
        'monthDir': '平',
        'monthJieFangSum': '2028.84',
        'yearDaiFangSum': '2028.84',
        'details': [{
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '2028.84',
          'yearMonth': '202103',
          'rowDir': '贷',
          'rowZhaiYao': '第一季度普票收入',
          'type': '记-003',
          'rowMoney': '2028.84',
          'pingZhengNum': 'PZ000000186'
        }, {
          'rowJieFangMoney': '2028.84',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '期间损益结转',
          'type': '记-010',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000193'
        }],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '6301 - 营业外收入'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '6401',
      'kuaiJiKeMuCodeName': '主营业务成本',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '129488.30',
        'yearJieFangSum': '129488.30',
        'monthDir': '平',
        'monthJieFangSum': '129488.30',
        'yearDaiFangSum': '129488.30',
        'details': [{
          'rowJieFangMoney': '129488.30',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '结转成本',
          'type': '记-008',
          'rowMoney': '129488.30',
          'pingZhengNum': 'PZ000000191'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '129488.30',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '期间损益结转',
          'type': '记-010',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000193'
        }],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '6401 - 主营业务成本'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '6403',
      'kuaiJiKeMuCodeName': '税金及附加',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '43.52',
        'yearJieFangSum': '43.52',
        'monthDir': '平',
        'monthJieFangSum': '43.52',
        'yearDaiFangSum': '43.52',
        'details': [{
          'rowJieFangMoney': '43.52',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '计提税金及附加',
          'type': '记-004',
          'rowMoney': '43.52',
          'pingZhengNum': 'PZ000000187'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '43.52',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '期间损益结转',
          'type': '记-010',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000193'
        }],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '6403 - 税金及附加'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '660210',
      'kuaiJiKeMuCodeName': '工资',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '15900.00',
        'yearJieFangSum': '15900.00',
        'monthDir': '平',
        'monthJieFangSum': '15900.00',
        'yearDaiFangSum': '15900.00',
        'details': [{
          'rowJieFangMoney': '5300.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '计提1月工资',
          'type': '记-005',
          'rowMoney': '5300.00',
          'pingZhengNum': 'PZ000000188'
        }, {
          'rowJieFangMoney': '5300.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '计提2月工资',
          'type': '记-006',
          'rowMoney': '10600.00',
          'pingZhengNum': 'PZ000000189'
        }, {
          'rowJieFangMoney': '5300.00',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '计提3月工资',
          'type': '记-007',
          'rowMoney': '15900.00',
          'pingZhengNum': 'PZ000000190'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '15900.00',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '期间损益结转',
          'type': '记-010',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000193'
        }],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '6602 - 管理费用'
    }, {
      'qichu': {'money': 0, 'jie': 0, 'dir': '平', 'dai': 0},
      'kuaiJiKeMuCode': '6801',
      'kuaiJiKeMuCodeName': '所得税费用',
      'month': [{
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '149.38',
        'yearJieFangSum': '149.38',
        'monthDir': '平',
        'monthJieFangSum': '149.38',
        'yearDaiFangSum': '149.38',
        'details': [{
          'rowJieFangMoney': '149.38',
          'rowDaiFangMoney': '0.00',
          'yearMonth': '202103',
          'rowDir': '借',
          'rowZhaiYao': '计提所得税',
          'type': '记-009',
          'rowMoney': '149.38',
          'pingZhengNum': 'PZ000000192'
        }, {
          'rowJieFangMoney': '0.00',
          'rowDaiFangMoney': '149.38',
          'yearMonth': '202103',
          'rowDir': '平',
          'rowZhaiYao': '期间损益结转',
          'type': '记-010',
          'rowMoney': '0.00',
          'pingZhengNum': 'PZ000000193'
        }],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }, {
        'monthDaiFangSum': '0.00',
        'yearJieFangSum': '0.00',
        'monthDir': '平',
        'monthJieFangSum': '0.00',
        'yearDaiFangSum': '0.00',
        'details': [],
        'monthMoney': '0.00'
      }],
      'range': ['202101', '202112'],
      'kuaiJiKeMuFirstLevelFullName': '6801 - 所得税费用'
    }], 'companyName': '', 'zhiBiaoRen': '', 'qujian': ['2021 - 01', '2021 - 12']
  }
